### ISSUE TITLE
New York next steps

### ISSUE THREAD

**Issue by zneedell** [LBNL-UCB-STI/beam#3399]
Summarizing next steps below, just to keep track of everything in one place

- [ ] Re-run existing NYC population for one scenario just to make sure everything works and populate skims
- [ ] Generate full (unsampled) population for the study area using existing SynthPop implementation and CTPP data. #3375 
- [ ] Add capability to choose leg modes during secondary activity planning. #3376 
- [ ] Add capability to stop BEAM after initial run of secondary activity planning module and dump plans. #3374
- [ ] Add capability to run a subset of output plans (in this case only transit trips) through R5 and collect/output information on the transit routes returned by R5 for each trip (specifically person enters/exits vehicle). #3400 
- [ ] Do all of this for the full population

**Comment by nikolayilyin** [comment]
Generation of plans and stopping the simulation -> https://github.com/LBNL-UCB-STI/beam/pull/3424
Merged into develop.

**Comment by heyrutvik** [comment]
Number of households = 3591665
Number of of people = 5681074
urbansim_v2 files: https://s3.us-east-2.amazonaws.com/beam-outputs/index.html#new_city/newyork/issue3399_subtask2/urbansim_v2_population_5m/

---

Number of households = 4633242
Number of of people = 12237368
urbansim_v2 files: https://s3.us-east-2.amazonaws.com/beam-outputs/index.html#new_city/newyork/issue3399_subtask2/urbansim_v2_population_12m/

---

Number of households: 4864508
Number of people: 13122080
branch: `rrp/#3399-full-population-home-activity-for-unemployed`
urbansim_v2 files: https://s3.us-east-2.amazonaws.com/beam-outputs/index.html#new_city/newyork/issue3399_subtask2/urbansim_v2_population_13m_unemployed_home_activity/

CRS = 'epsg:32118'
Note: to create conditional work duration csv, we have used `{35620:0.6, '-':0.4}` param. (`New York-Newark-Jersey City, NY-NJ-PA`)
