### ISSUE TITLE
Enable parallelization of work via parallelization

### ISSUE THREAD

**Issue by JustinPihony** [LBNL-UCB-STI/beam#342]
Requirements:
- [x] Upgrade to Akka 2.5 - parent of #343 
- [x] Clustering should be configurable so that the single JVM approach still works by default - parent of #345
- [x] Make sure that dropped messages are retried up to a configurable value - parent of #344
